package welink.system
/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                if (controllerName == 'callback' || controllerName == 'assets') return true
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true;
                // Ignore rest api
                if (controllerName.startsWith("open")) {
                    return true;
                }
                // Access control by convention.
                accessControl()
            }
        }
    }
}
